# Generated by Django 5.1.1 on 2024-10-05 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_tempcartoon_user'),
        ('main', '0033_profile_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcartoon',
            name='cartoon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cartoons'),
        ),
    ]
