# Generated by Django 4.2.7 on 2023-11-21 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0013_delete_mylistobject_delete_mylistscores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyListScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='MyListStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус просмотра',
                'verbose_name_plural': 'Статусы просмотра',
            },
        ),
        migrations.CreateModel(
            name='MyListObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=750)),
                ('times_rewatched', models.SmallIntegerField(default=1)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartoons')),
                ('score', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='myList.mylistscores')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('watch_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myList.myliststatus')),
            ],
            options={
                'verbose_name': 'Обьект списка',
                'verbose_name_plural': 'Обьекты списков',
            },
        ),
    ]
