# Generated by Django 4.2.7 on 2023-12-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0003_alter_mylistobject_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='myliststatus',
            name='priority_in_list',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
