# Generated by Django 4.2.7 on 2023-11-10 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartoonsGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='CartoonsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='CartoonsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Cartoons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_title', models.CharField(max_length=255)),
                ('rus_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('number_of_ratings', models.IntegerField()),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField(blank=True)),
                ('number_of_seasons', models.PositiveSmallIntegerField()),
                ('number_of_series', models.PositiveSmallIntegerField()),
                ('studio', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='covers')),
                ('is_published', models.BooleanField(default=True)),
                ('age_restrictions', models.PositiveSmallIntegerField(blank=True)),
                ('creators', models.SmallIntegerField(blank=True)),
                ('genres', models.ManyToManyField(to='main.cartoonsgenres')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cartoonsstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cartoonstypes')),
            ],
            options={
                'verbose_name': 'Мультфильм',
                'verbose_name_plural': 'Мультфильмы',
            },
        ),
    ]
