# Generated by Django 4.2.7 on 2023-11-10 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='number_of_ratings',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='number_of_seasons',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='number_of_series',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='start_year',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.cartoonsstatus'),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='studio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.cartoonstypes'),
        ),
    ]
