# Generated by Django 4.2.7 on 2023-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cartoons_cover_alter_cartoons_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='genres',
            field=models.ManyToManyField(blank=True, to='main.cartoonsgenres'),
        ),
    ]
