# Generated by Django 4.2.7 on 2023-11-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyListStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Статус от пользователя',
                'verbose_name_plural': 'Статусы от пользователей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
