# Generated by Django 4.2.7 on 2023-11-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myliststatus_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myliststatus',
            options={'verbose_name': 'Статус просмотра', 'verbose_name_plural': 'Статусы просмотра'},
        ),
    ]
