# Generated by Django 4.2.7 on 2023-11-21 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_alter_myliststatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyListObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(blank=True)),
                ('comment', models.TextField(blank=True, max_length=750)),
                ('times_rewatched', models.SmallIntegerField(default=1)),
                ('cartoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cartoons')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('watch_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.myliststatus')),
            ],
        ),
    ]
