# Generated by Django 4.2.7 on 2023-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mylistobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylistobject',
            options={'verbose_name': 'Обьект списка', 'verbose_name_plural': 'Обьекты списков'},
        ),
    ]
