# Generated by Django 4.2.7 on 2023-11-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_mylistobject_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyListObject',
        ),
        migrations.DeleteModel(
            name='MyListScores',
        ),
        migrations.DeleteModel(
            name='MyListStatus',
        ),
    ]
