# Generated by Django 4.2.7 on 2023-12-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_mylistobject_delete_mylistscores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoons',
            options={'ordering': ['-rating'], 'verbose_name': 'Мультсериал', 'verbose_name_plural': 'Мультсериалы'},
        ),
        migrations.AlterModelOptions(
            name='cartoonsstatus',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='cartoonsstatus',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartoonstypes',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
