# Generated by Django 4.2.7 on 2023-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cartoonsstatus_eng_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoonsstatus',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cartoonstypes',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
