# Generated by Django 4.2.7 on 2023-12-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_cartoonsstatus_eng_name_cartoonstypes_eng_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoonsgenres',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
