# Generated by Django 4.2.7 on 2023-12-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_cartoonsgenres_eng_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
