# Generated by Django 4.2.7 on 2023-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_cartoons_end_year_remove_cartoons_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoons',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartoons',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
