# Generated by Django 4.2.7 on 2023-12-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_cartoons_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoons',
            name='studio',
        ),
    ]
