# Generated by Django 4.2.7 on 2023-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cartoons_studio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoons',
            name='studio',
        ),
        migrations.AddField(
            model_name='cartoons',
            name='studios',
            field=models.ManyToManyField(blank=True, null=True, to='main.studios'),
        ),
    ]
