# Generated by Django 4.2.7 on 2023-12-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_cartoons_studio_cartoons_studios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoons',
            name='studios',
        ),
    ]
