# Generated by Django 4.2.7 on 2023-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_cartoons_studios'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoons',
            name='studios',
            field=models.ManyToManyField(blank=True, null=True, to='main.studios'),
        ),
    ]
