# Generated by Django 4.2.7 on 2023-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_cartoons_studios'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_list_public',
            field=models.BooleanField(default=True),
        ),
    ]
