# Generated by Django 4.2.7 on 2023-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_profile_is_list_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cover_in_list',
            field=models.BooleanField(default=True),
        ),
    ]
