# Generated by Django 5.1.1 on 2024-10-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_profile_is_cover_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoons',
            name='number_of_ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartoons',
            name='rating',
            field=models.FloatField(default=7.0),
        ),
    ]
