# Generated by Django 5.1.1 on 2024-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_cartoons_number_of_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoons',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
